### ISSUE TITLE
Determine Equipment Point availability

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#420]
### Context

The `Harvest` model currently has a `equipment_reserved` _ManyToMany_ field because in the legacy version it used to be possible reserve one or more `Equipment` for a harvest. 
https://github.com/LesFruitsDefendus/saskatoon-ng/blob/3308f376fa89b210b1be4ba02264f411967d0568/saskatoon/harvest/models.py#L481

**I suggest we keep working with this existing field, even if as a first iteration we are only interested in booking a single _Equipment Point_**. This will allow us to add more granularity further down the road, e.g.:
- support multiple Harvests sharing the same Equipment Point
- support a single Harvest borrowing equipment from two different Equipment Points

### Definitions:

-  for a given `Harvest`,  _reserving_ an _Equipment Point_ means that **all** equipment registered for the `Organization` is booked at once, i.e. all items are added to the `equipment_reserved` list for this `Harvest`.
- an _Equipment Point_ is considered _unavailable_ for a given timeslot if at least one of its equipment is reserved by an _active_ Harvest whose _time range_ overlaps with the timeslot. 
- a Harvest is considered _active_ if its status is either _Scheduled_ or _Ready_ and it is not in the past. 
- the _time range_ during which a Harvest reserves an equipment point should be `start_date - buffer` -> `end_date + buffer`, where `buffer` is a constant time delta (e.g. 1hour) to give enough time for pickleaders to pickup/return the equipment before/after the harvest. 

### Tasks:

- [x] Create a utility function that lists all available equipment points for a given datetime range
- [x] Route the  [EquipmentPointAutocomplete](https://github.com/LesFruitsDefendus/saskatoon-ng/blob/main/saskatoon/member/autocomplete.py#L114) and expand it to allow filtering by datetime range. When passed a `start_date`/`end_date` the `equipment-point-autocomplete/` enpoint should return all Equipment Points that are _available_ for this datetime range.
- [ ] Update fixtures to have at least one Harvest with a reserved equipment point
- [ ] Add unit tests to thoroughly test the utility function
- [ ] The reservation buffer should be parameterized
